name: Python testing

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  test:
    env:
      # Have the venv be in the project folder so it is easier to cache
      PIPENV_VENV_IN_PROJECT: true
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python_version: [3.6]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python_version }}
    - name: Install pipenv
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
    - name: Cache virtualenv
      uses: actions/cache@v2
      env:
        CACHE_NAME: CACHE_VIRTUALENV
      with:
        path: .venv
        key: >
          ${{ runner.os }}-${{ env.CACHE_NAME }}-${{ matrix.python_version }}-testing-${{ hashFiles('Pipfile.lock') }}
        # Fallbacks to partially restore cache
        restore-keys: |
          ${{ runner.os }}-${{ env.CACHE_NAME }}-${{ matrix.python_version }}-testing-
          ${{ runner.os }}-${{ env.CACHE_NAME }}-${{ matrix.python_version }}-
          ${{ runner.os }}-${{ env.CACHE_NAME }}-

    - name: Install dependencies
      run: |
        pipenv install --deploy
    - name: Run tests
      run: |
        pipenv run python manage.py test
